#!/usr/bin/env ruby

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'aws-sdk', require: true
end

$stdout.sync = true

expected = ENV['ID']

creds = Aws::Credentials.new(ENV['AWS_ACCESS_KEY_ID'], ENV['AWS_SECRET_ACCESS_KEY'])
client = Aws::Lambda::Client.new(region: region, credentials: creds)

def poll(client)
  resp = client.invoke(
    client_context: 'dpl-test',
    function_name: 'dpl-test',
    invokation_type: 'Event'
  )
  p resp
  p resp.payload
rescue => e
  puts e.message
end

20.times do
  actual = poll(client)
  actual = uri.read
  puts "expected: #{expected.inspect}"
  puts "actual: #{actual.inspect}"
  exit 0 if actual == expected
  sleep 5
end

abort 'failed'
